### ISSUE TITLE
Capcom Jojo PS2 Game Tim2 Files unrecognized in most programs

### ISSUE THREAD

**Issue by num421337** [lab313ru/tim2view#10]
I've tried everything I can think of and am grasping at straws here. But either way.  I've gotten a limited amount of tim2 files working from this game but the majority seems like they are compressed/encrypted or something. Here's an example file containing a few tim2 files inside it that I located using a hex editor. If you could look at them it would be greatly appreciated
[demo.zip](https://github.com/lab313ru/tim2view/files/4345957/demo.zip)

**Comment by lab313ru** [comment]
Sorry, but tim2 still not supported and it won't be.
