### ISSUE TITLE
TIM has 26214 colors while it has zero

### ISSUE THREAD

**Issue by aybe** [lab313ru/tim2view#11]
Game = `Ridge Racer Bonus Turbo Mode Disc (USA)`
File = `RR60/TEX0.PIM`
SHA1 = `AC9667CD103C9DA1B640D4EA9771314B074BA4B3`

It says 26214 colors but there's no CLUT, I checked with an hex editor:

![tim2view_win64_x86_64_2020-11-23_20-56-29](https://user-images.githubusercontent.com/1537591/100008931-60793080-2dce-11eb-8427-87c8c7c40804.png)

Thanks 😀

**Comment by lab313ru** [comment]
Hello, thanks for a bug. Don't sure about fixing it, and about this project 
future. Sorry.

aybe <notifications@github.com> 23 ноября 2020 г. 22:58:09 написал:

**Comment by aybe** [comment]
Okay, thank you mate ;)
