### ISSUE TITLE
Cannot find unit BGRABitmap

### ISSUE THREAD

**Issue by gwald** [lab313ru/tim2view#3]
Hi 
I found your app on 
http://www.psxdev.net/forum/viewtopic.php?f=60&t=530
I've install lazarus and the master source click run-> build and get:
udrawtim.pas(6,33) Fatal: Cannot find unit BGRABitmap used by udrawtim of the Project Inspector.

I'm a complete pascal/lazarus noob but I assume BGRABitmap is an external lib?

**Comment by lab313ru** [comment]
You should clone submodule too with this command:
`git submodule update --init --recursive`

**Comment by gwald** [comment]
Cool thanks, i'll give it a try on the weekend.
cheers
